---

included:
  - Package.swift
  - src

disabled_rules:
  - trailing_comma

# Rule Configuration

nesting:
  type_level: 2

type_name:
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false
